name: Test dagger
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Set up python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.11
      - name: Make cache dir
        run: |
          mkdir -p /tmp/output-dagger
          touch /tmp/output-dagger/one.txt
      - name: Caching
        uses: actions/cache@v3.2.3
        with:
          path: |
            /tmp/output-dagger
          key: cache-Py2.7-Plone4.3
      - name: Prepare use of cache
        run: |
          mkdir cache
          cp -r /tmp/output-dagger/* cache
      - name: Install dagger
        run: |
          pip install dagger-io
      - name: Run tests
        run: |
          python main.py
